# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'Neverthink5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Neverthink5

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  target 'Neverthink5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Neverthink5-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Neverthink5-tvOS

  target 'Neverthink5-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod "YoutubePlayer-in-WKWebView", "~> 0.3.4"
